# Generated by Django 2.0.2 on 2018-02-03 15:21

from django.db import migrations, models
import django.db.models.deletion
import talks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('language', models.CharField(choices=[('polish', 'Polish'), ('english', 'English')], max_length=16)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('slides', models.FileField(blank=True, null=True, upload_to=talks.models.talk_slides_upload)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='talks.Talk'),
        ),
    ]
